#!/bin/sh

LIST=$(dirname $(which ${0}))/triples.txt
LOGS=$(dirname $(which ${0}))/../logs
BINS=$(dirname $(which ${0}))/../output

CSUF=cross
NSUF=native

KALE="${PATH}"
OVER=""

optics()
{
    case ${1} in
        *microblaze*)
            # ICE in GCC; temporarily disable gfortran support.
            # https://gcc.gnu.org/bugzilla/show_bug.cgi?id=87438
            OVER="GCC_CONFIG=\"--enable-languages=c,c++\""
            ;;
        *)
            OVER=""
            ;;
    esac
}

mkdir -p ${LOGS} ${BINS}
for t in $(cat ${LIST} | grep -v "#"); do
    [ -d ${BINS}/${t}-${CSUF} ] || make ${OVER} install \
        TARGET=${t} OUTPUT=${BINS}/${t}-${CSUF} \
        -j$(nproc) 2>&1 | tee ${LOGS}/${t}-${CSUF}.log
    if [ -d ${BINS}/${t}-${CSUF} ]; then
        export PATH="${KALE}:${BINS}/${t}-${CSUF}/bin"
        [ -d ${BINS}/${t}-${NSUF} ] || make ${OVER} install NATIVE=1 \
            TARGET=${t} CROSS_COMPILE=${t}- OUTPUT=${BINS}/${t}-${NSUF} \
            -j$(nproc) 2>&1 | tee ${LOGS}/${t}-${NSUF}.log
        export PATH="${KALE}"
    fi;
done;

cd ${BINS}
for t in $(find . -mindepth 1 -maxdepth 1 -type d); do
    [ -e ${t}.tgz ] || tar pczf ${t}.tgz ${t};
done
